name: erasmus_app_discover
description: Applicazione destinata agli esploratori del nostro territorio, frutto del progetto Erasmus+ EWW21/22
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dio: ^4.0.6
  chopper: ^4.0.5
  json_serializable: ^6.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
