server:
  port: 8002
spring:
  application:
    name: ErasmusApp_WS_Login
  datasource:
    username: ErasmusAPP_Login
    password: ErasmusAPP_Login
    url: jdbc:mariadb://localhost:3306/ErasmusApp
  # initialization-mode: always
  sql:
    init:
      mode: always
      platform: mariadb
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher